services:
  mysql:
    image: mysql:latest
    container_name: mysql_db
    hostname: host.docker.internal
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: abc
      MYSQL_ROOT_PASSWORD: abc
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - my_network


volumes:
  db:
    driver: local

networks:
  my_network:

